name: Simple PR Check

on:
  pull_request:
    branches:
      - main # Chạy khi có PR vào nhánh 'main'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Kéo mã nguồn về

      - name: Say Hello
        run: echo "Hello! This GitHub Action is running for your Pull Request!"